@startuml

title __UI's Class Diagram__\n

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.AlertBox {
          {static} + display()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.CheatMenu {
          {static} + INCREASE_VALUE : int
          {static} + MIN_HEALTH : int
          {static} + display()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.ConfirmBox {
          {static} ~ answer : Boolean
          {static} + display()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.GameOverBox {
          {static} + display()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.GetPlayerNameAlertBox {
          {static} + display()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.InventoryBox {
          ~ inventory : List<Item>
          ~ window : Stage
          + display()
          - createBodyArmorButtonIfExists()
          - createHeadgearButtonIfExists()
          - createHealtbutton()
          - createLeftLegArmorButtonIfExists()
          - createManaButton()
          - createRightLegArmorButtonIfExists()
          - createSetFromInventory()
          - getNumberOfElements()
          - initBorderPane()
          - initCloseButton()
          - initGridPane()
          - initHeadgearButtonEventListener()
          - initUi()
          - initVBox()
          - inventoryToString()
          - onKeyPressed()
          - removeItem()
          - turnRandomEnemyToFire()
          - usePotion()
      }
    }
  }
  

  namespace com.codecool.dungeoncrawl {
    namespace UI {
      class com.codecool.dungeoncrawl.UI.WinGameBox {
          {static} + display()
      }
    }
  }
  

  com.codecool.dungeoncrawl.UI.InventoryBox o-- com.codecool.dungeoncrawl.logic.Cell : cell


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
